services:
  organize:
    image: organize:arm64
    container_name: organize
    environment:
      - TZ=Europe/London
    volumes:
      - ./organize/config:/config
      - ./downloads:/downloads
      - ./media:/media
    command: ["run", "/config/config.yml"]
    restart: "no"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Europe/London
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    ports:
      - "19999:19999"
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=postgres
    volumes:
      - ./nextcloud:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8081:8080"
    restart: unless-stopped
